class RequirementWarning:
    # 意图层
    MULTIPLE_INTENTS = "MULTIPLE_INTENTS"
    CORE_INTENT_WEAK = "CORE_INTENT_WEAK"

    # 范围 / 边界
    AMBIGUOUS_SCOPE = "AMBIGUOUS_SCOPE"
    UNCLEAR_TARGET = "UNCLEAR_TARGET"

    # 实体 / 操作
    MISSING_KEY_ENTITY = "MISSING_KEY_ENTITY"
    UNKNOWN_ENTITY = "UNKNOWN_ENTITY"
    OPERATION_UNCLEAR = "OPERATION_UNCLEAR"

    # 约束 / 非功能
    CONSTRAINT_MISSING = "CONSTRAINT_MISSING"
    NON_FUNCTIONAL_UNCLEAR = "NON_FUNCTIONAL_UNCLEAR"

    # 语境 / 领域
    DOMAIN_UNCERTAIN = "DOMAIN_UNCERTAIN"
    STAGE_UNCERTAIN = "STAGE_UNCERTAIN"

    # 隐含信息风险
    IMPLICIT_ASSUMPTION_HEAVY = "IMPLICIT_ASSUMPTION_HEAVY"
